## A pair of functions that cache the inverse of a matrix

## Creates a special matrix "matrix" object which is actually a list. It can cache its own inverse.

makeCacheMatrix <- function(x = matrix()) {
        i <- NULL
        set <- function(y) {
                m <<- y
                i <<- NULL
        }
        get <- function () m
        setinv <- function(inverse) i <<- inverse
        getinv <- function() i
        list(set = set, get = get,
             setinv = setinv, getinv = getinv)
}


## Computes the inverse of the "matrix" object generated by the function above. If the inverse has already been computed, 
## it is retrieved from the cache.

cacheSolve <- function(x, ...) {
        i <- x$getinv()
        if(!is.null(i)) {
                message("getting cached data")
                return(i)
        }
        data <- x$get()
        i <- solve(data)
        x$setinv(i)
        i
}
